name: Metrics

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          user: Roncospina

          # ğŸ¨ DiseÃ±o base
          template: classic
          base: header, metadata

          # ğŸ§  Introduction
          plugin_introduction: yes
          plugin_introduction_title: yes
          plugin_introduction_description: yes

          # ğŸ¢ Organizaciones
          plugin_organizations: yes

          # ğŸ· Topics
          plugin_topics: yes
          plugin_topics_limit: 12

          # ğŸŒ Lenguajes
          plugin_languages: yes
          plugin_languages_limit: 8
          plugin_languages_details: percentage

          # ğŸ† Achievements
          plugin_achievements: yes
          plugin_achievements_display: compact

          # ğŸ”¥ Actividad reciente
          plugin_activity: yes
          plugin_activity_limit: 5

          # ğŸµ MÃºsica (Spotify)
          plugin_music: yes
          plugin_music_provider: spotify
          plugin_music_token: ${{ secrets.SPOTIFY_TOKEN }}
